package com.inspirage.ilct.enums;

public enum ActionEnum {

    SAVING_SHIPMENT, UPDATING_SHIPMENT, FINDING_SHIPMENT, FINDING_SHIPMENT_TRACKING, X3_TRIGGERED, AF_TRIGGERED, GVIT_TRIGGERED, X1_TRIGGERED, D1_TRIGGERED, CLOSED_SHIPMENT, X6_TRIGGERED, AG_TRIGGERED, SAVING_SHIPMENT_STATUS, CLOSING_SHIPMENT, IOT_SHIPMENT_STATUS, SAVING_ALERTS, UPDATING_ALERTS, FINDING_ALERTS, DELETING_ALERTS, SAVING_APPLICATION_SETTINGS, UPDATING_APPLICATION_SETTINGS, SAVING_FILE, DOWNLOADING_FILE, UPLOADING_FILE, SAVING_MONITOR, UPDATING_MONITOR, FINDING_MONITOR, DELETING_MONITOR, SET_RULES, PAGE_REDIRECTION, FINDING_STOPS, FINDING_EVENTS, FINDING_SHIPMENTS_INTRANSIT, FINDING_SHIPMENTS_COMPLETED, SAVING_ROLE, FINDING_ROLE
}
