package com.inspirage.ilct.util;

public enum SearchResultPageConstant {

    MAP_VEHICLE_VISIBILITY, MAP_ITEM_VISIBILITY, TABLE_VEHICLE_VISIBILITY, COMPLETED, MAP_CONTAINER_VISIBILITY, CONTAINER_VISIBILITY_TABLE,     PARCEL_VISIBILITY_TABLE,
    TABLE_CONTAINER_VISIBILITY
}
