<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="xml" indent="yes"/>
    <xsl:strip-space elements="*"/>
    <xsl:template match="/">
        <otm:Transmission xmlns:otm="http://xmlns.oracle.com/apps/otm/transmission/v6.4">
            <otm:TransmissionHeader>
                <otm:SenderTransmissionNo>
                    <xsl:value-of select="/Feed/FeedHeader/FeedRefNum"/>
                </otm:SenderTransmissionNo>
                <otm:AckSpec>
                    <otm:ComMethodGid>
                        <otm:Gid>
                            <otm:Xid>EMAIL</otm:Xid>
                        </otm:Gid>
                    </otm:ComMethodGid>
                    <otm:AckOption>ERROR</otm:AckOption>
                    <otm:ContactGid>
                        <otm:Gid>
                            <otm:DomainName>
                                <xsl:value-of
                                        select="substring-before(/Feed/FeedContent/ILMCTOutXML/StatusUpdate/LoadId,'.')"/>
                            </otm:DomainName>
                            <otm:Xid>SUPPORT</otm:Xid>
                        </otm:Gid>
                    </otm:ContactGid>
                </otm:AckSpec>
                <otm:Refnum>
                    <otm:RefnumQualifierGid>
                        <otm:Gid>
                            <otm:DomainName>
                                <xsl:value-of
                                        select="substring-before(/Feed/FeedContent/ILMCTOutXML/StatusUpdate/LoadId,'.')"/>
                            </otm:DomainName>
                            <otm:Xid>MESSAGE_TYPE</otm:Xid>
                        </otm:Gid>
                    </otm:RefnumQualifierGid>
                    <otm:RefnumValue>ILMCT_ETA_UPDATE</otm:RefnumValue>
                </otm:Refnum>
            </otm:TransmissionHeader>
            <otm:TransmissionBody>
                <otm:GLogXMLElement>
                    <otm:TransactionHeader>
                        <otm:Refnum>
                            <otm:RefnumQualifierGid>
                                <otm:Gid>
                                    <otm:DomainName>
                                        <xsl:value-of
                                                select="substring-before(/Feed/FeedContent/ILMCTOutXML/StatusUpdate/LoadId,'.')"/>
                                    </otm:DomainName>
                                    <otm:Xid>MESSAGE_TYPE</otm:Xid>
                                </otm:Gid>
                            </otm:RefnumQualifierGid>
                            <otm:RefnumValue>ILMCT_STATUS_UPDATE</otm:RefnumValue>
                        </otm:Refnum>
                    </otm:TransactionHeader>
                    <otm:GenericStatusUpdate>
                        <otm:GenericStatusObjectType>SHIPMENT</otm:GenericStatusObjectType>
                        <otm:Gid>
                            <otm:DomainName>
                                <xsl:value-of
                                        select="substring-before(/Feed/FeedContent/ILMCTOutXML/StatusUpdate/LoadId,'.')"/>
                            </otm:DomainName>
                            <otm:Xid>
                                <xsl:value-of
                                        select="substring-after(/Feed/FeedContent/ILMCTOutXML/StatusUpdate/LoadId,'.')"/>
                            </otm:Xid>
                        </otm:Gid>
                        <otm:TransactionCode>U</otm:TransactionCode>
                        <otm:Status>
                            <otm:StatusTypeGid>
                                <otm:Gid>
                                    <otm:DomainName>
                                        <xsl:value-of
                                                select="substring-before(/Feed/FeedContent/ILMCTOutXML/StatusUpdate/LoadId,'.')"/>
                                    </otm:DomainName>
                                    <otm:Xid>ILMCT_STATUS</otm:Xid>
                                </otm:Gid>
                            </otm:StatusTypeGid>
                            <otm:StatusValueGid>
                                <otm:Gid>
                                    <otm:DomainName>
                                        <xsl:value-of
                                                select="substring-before(/Feed/FeedContent/ILMCTOutXML/StatusUpdate/LoadId,'.')"/>
                                    </otm:DomainName>
                                    <otm:Xid>
                                        <xsl:value-of select="/Feed/FeedContent/ILMCTOutXML/StatusUpdate/Status"/>
                                    </otm:Xid>
                                </otm:Gid>
                            </otm:StatusValueGid>
                        </otm:Status>
                    </otm:GenericStatusUpdate>
                </otm:GLogXMLElement>
                <otm:GLogXMLElement>
                    <otm:TransactionHeader>
                        <otm:Refnum>
                            <otm:RefnumQualifierGid>
                                <otm:Gid>
                                    <otm:DomainName>
                                        <xsl:value-of
                                                select="substring-before(/Feed/FeedContent/ILMCTOutXML/StatusUpdate/LoadId,'.')"/>
                                    </otm:DomainName>
                                    <otm:Xid>MESSAGE_TYPE</otm:Xid>
                                </otm:Gid>
                            </otm:RefnumQualifierGid>
                            <otm:RefnumValue>ILMCT_ETA_UPDATE</otm:RefnumValue>
                        </otm:Refnum>
                    </otm:TransactionHeader>
                    <otm:ShipStop>
                        <otm:ShipmentGid>
                            <otm:Gid>
                                <otm:DomainName>
                                    <xsl:value-of
                                            select="substring-before(/Feed/FeedContent/ILMCTOutXML/StatusUpdate/LoadId,'.')"/>
                                </otm:DomainName>
                                <otm:Xid>
                                    <xsl:value-of
                                            select="substring-after(/Feed/FeedContent/ILMCTOutXML/StatusUpdate/LoadId,'.')"/>
                                </otm:Xid>
                            </otm:Gid>
                        </otm:ShipmentGid>
                        <otm:TransactionCode>U</otm:TransactionCode>
                        <otm:ShipmentStop>
                            <otm:StopSequence>
                                <xsl:value-of select="/Feed/FeedContent/ILMCTOutXML/ETAUpdate/StopNum"/>
                            </otm:StopSequence>
                            <otm:TransactionCode>IU</otm:TransactionCode>
                            <otm:ArrivalTime>
                                <otm:EventTime>
                                    <otm:EstimatedTime>
                                        <otm:GLogDate>
                                            <xsl:value-of select="/Feed/FeedContent/ILMCTOutXML/ETAUpdate/ETA/DateTime"/>
                                        </otm:GLogDate>
                                        <otm:TZId>
                                            <xsl:value-of select="/Feed/FeedContent/ILMCTOutXML/ETAUpdate/ETA/TimeZone"/>
                                        </otm:TZId>
                                    </otm:EstimatedTime>
                                </otm:EventTime>
                            </otm:ArrivalTime>
                            <otm:DepartureTime>
                                <otm:EventTime>
                                    <otm:EstimatedTime>
                                        <otm:GLogDate>
											<xsl:value-of select="/Feed/FeedContent/ILMCTOutXML/ETAUpdate/ETD/DateTime"/>
                                        </otm:GLogDate>
                                        <otm:TZId>
											<xsl:value-of select="/Feed/FeedContent/ILMCTOutXML/ETAUpdate/ETD/TimeZone"/>
                                        </otm:TZId>
                                    </otm:EstimatedTime>
                                </otm:EventTime>
                            </otm:DepartureTime>
                        </otm:ShipmentStop>
                    </otm:ShipStop>
                </otm:GLogXMLElement>
            </otm:TransmissionBody>
        </otm:Transmission>

    </xsl:template>
</xsl:stylesheet>